[workspace]
resolver = "2"
members = [
    "crates/core-storage",
    "crates/core-storage-platform",

    "crates/core-storage-cli",
    # "crates/*",
]

[workspace.package]
version = "0.0.1"
edition = "2024"
authors = ["Tuan ca"]
license = "MIT"
repository = "https://github.com/tuanca2503/core-storage"

[workspace.dependencies]
chrono = { version = "0.4.45", default-features = false, features = [
    "serde",
    "clock",
    "std",
] }
serde = { version = "1.0.228", default-features = false, features = [
    "derive",
    "std",
] }
serde_json = { version = "1.0.150", default-features = false, features = [
    "std",
] }
tracing = { version = "0.1.44", default-features = false, features = ["std"] }

