[package]
name = "database"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
platform = { path = "../platform" }


tokio = { workspace=true }
rusqlite = { version = "0.40.0", features = ["bundled"] }
r2d2 = "0.8"
r2d2_sqlite = "0.35.0"