[package]
name = "core-storage-platform"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
uuid = { version = "1.23.5", features = ["v7"] }
chrono = {workspace=true}


[target.'cfg(target_os = "windows")'.dependencies]
windows = { version = "0.62", features = [
    "Win32_Foundation",
    "Win32_Storage_FileSystem",
    "Win32_System_IO",
    "Win32_System_Ioctl",
    "Win32_Devices_DeviceAndDriverInstallation",
    "Win32_Security",
] }

[target.'cfg(target_os = "linux")'.dependencies]
crc32c = "0.6"
hex = "0.4"
libc = "0.2"
