[package]
name = "core-storage"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
core-storage-platform = { path = "../core-storage-platform" }
rusqlite = {version = "0.40.1", features = ["bundled"]}
sysinfo = "0.39.6"
chrono = { workspace = true }
