[package]
name = "core-storage-cli"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
core-storage = { path = "../core-storage" }
core-storage-platform = { path = "../core-storage-platform" }
serde = { workspace=true }
serde_json = {workspace=true}
