[package]
name = "daemon"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
model = { path = "../model" }
database = { path = "../database" }
service = { path = "../service" }
platform = { path = "../platform" }
api = { path = "../api" }




chrono = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
tracing-appender  = { workspace = true }

async-trait = "0.1"




